# Generated by Django 4.1.3 on 2022-12-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="character_art"),
        ),
    ]
