# Generated by Django 4.1.3 on 2022-12-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0002_character_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="character", name="slug", field=models.SlugField(null=True),
        ),
    ]
