# Generated by Django 4.1.3 on 2022-12-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0005_technique_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="multitarget",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                max_length=100,
                null=True,
            ),
        ),
    ]
