# Generated by Django 4.1.3 on 2022-12-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0006_technique_multitarget"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="area",
            field=models.CharField(
                choices=[("small", "small"), ("medium", "medium"), ("large", "large")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="range",
            field=models.CharField(
                choices=[
                    ("reach", "reach"),
                    ("near", "near"),
                    ("far", "far"),
                    ("remote", "remote"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="multitarget",
            field=models.CharField(
                choices=[("2", "2"), ("3", "3"), ("4", "4")], max_length=100, null=True
            ),
        ),
    ]
