# Generated by Django 4.1.3 on 2022-12-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0007_technique_area_technique_range_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="combo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="technique",
            name="controlled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="technique",
            name="cure",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="technique",
            name="destructive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="technique",
            name="disarm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="technique",
            name="forceful",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="technique",
            name="frightning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="technique",
            name="heal",
            field=models.CharField(
                choices=[("1", "50%"), ("2", "100%")],
                default="50%",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="immobilizing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="technique",
            name="piercing",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="technique",
            name="area",
            field=models.CharField(
                choices=[
                    ("none", "none"),
                    ("small", "small"),
                    ("medium", "medium"),
                    ("large", "large"),
                ],
                default="none",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="multitarget",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                default="1",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="range",
            field=models.CharField(
                choices=[
                    ("touch", "touch"),
                    ("reach", "reach"),
                    ("near", "near"),
                    ("far", "far"),
                    ("remote", "remote"),
                ],
                default="touch",
                max_length=100,
                null=True,
            ),
        ),
    ]
