# Generated by Django 4.1.3 on 2023-01-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0009_technique_armor_shred_technique_practiced_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="character_art"
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="area",
            field=models.CharField(
                choices=[
                    ("none", "none"),
                    ("small", "small"),
                    ("medium", "medium"),
                    ("large", "large"),
                ],
                default="none",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="heal",
            field=models.CharField(
                choices=[("0", "0%"), ("1", "50%"), ("2", "100%")],
                default="0",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="multitarget",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                default="1",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="range",
            field=models.CharField(
                choices=[
                    ("touch", "touch"),
                    ("reach", "reach"),
                    ("near", "near"),
                    ("far", "far"),
                    ("remote", "remote"),
                ],
                default="touch",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="summon",
            field=models.CharField(
                choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3")],
                default="0",
                max_length=100,
            ),
        ),
    ]
