# Generated by Django 4.1.3 on 2023-01-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0018_alter_technique_summon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="boon",
            field=models.BooleanField(default=False),
        ),
    ]
