# Generated by Django 4.1.3 on 2023-02-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0021_technique_subtle"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="mobile",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="technique",
            name="subtle",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
