# Generated by Django 4.1.3 on 2023-02-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0022_technique_mobile_alter_technique_subtle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="mobile",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
