# Generated by Django 4.1.3 on 2023-03-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0025_rename_immobilizing_technique_restricting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="max_cost",
            field=models.IntegerField(default=0),
        ),
    ]
