# Generated by Django 4.1.3 on 2023-04-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0026_technique_max_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="forceful",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="technique",
            name="lasting",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="technique",
            name="mobile",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="technique",
            name="power",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="technique",
            name="subtle",
            field=models.BooleanField(default=False),
        ),
    ]
