# Generated by Django 4.1.3 on 2023-04-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0027_alter_technique_forceful_alter_technique_lasting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="level",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
