# Generated by Django 4.1.3 on 2023-04-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0028_alter_character_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="public",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
