# Generated by Django 4.1.3 on 2023-04-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0029_technique_public"),
    ]

    operations = [
        migrations.RenameField(
            model_name="technique", old_name="frightning", new_name="frightening",
        ),
    ]
