# Generated by Django 4.1.3 on 2023-04-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0030_rename_frightning_technique_frightening"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="forceful",
            field=models.CharField(
                choices=[("0", "Normal"), ("1", "Strong"), ("2", "Excessive")],
                default="0",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="technique",
            name="piercing",
            field=models.CharField(
                choices=[
                    ("0", "None"),
                    ("1", "Armor Piercing"),
                    ("2", "Armor Shredding"),
                ],
                default="0",
                max_length=100,
            ),
        ),
    ]
