# Generated by Django 4.1.3 on 2023-04-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0031_alter_technique_forceful_alter_technique_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique", name="content", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="technique",
            name="piercing",
            field=models.CharField(
                choices=[
                    ("0", "None"),
                    ("1", "armor piercing"),
                    ("2", "armor shredding"),
                ],
                default="0",
                max_length=100,
            ),
        ),
    ]
