# Generated by Django 4.1.3 on 2022-12-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0003_character_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="technique",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
