# Generated by Django 4.1.3 on 2022-12-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0004_alter_character_name_alter_character_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
