# Generated by Django 4.1.3 on 2023-01-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0010_alter_character_image_alter_technique_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="area",
            field=models.CharField(
                choices=[
                    (0, "none"),
                    ("small", "small"),
                    ("medium", "medium"),
                    ("large", "large"),
                ],
                default="none",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="heal",
            field=models.CharField(
                choices=[(0, "0%"), (1, "50%"), (2, "100%")],
                default="0",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="multitarget",
            field=models.CharField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                default="1",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="summon",
            field=models.CharField(
                choices=[(0, "NA"), (1, "1"), (2, "2"), (3, "3")],
                default="0",
                max_length=100,
            ),
        ),
    ]
