# Generated by Django 4.1.3 on 2023-01-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0011_alter_technique_area_alter_technique_heal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="area",
            field=models.CharField(
                choices=[(0, "none"), (1, "small"), (2, "medium"), (3, "large")],
                default="none",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="range",
            field=models.CharField(
                choices=[
                    (0, "touch"),
                    (1, "reach"),
                    (2, "near"),
                    (3, "far"),
                    (4, "remote"),
                ],
                default="touch",
                max_length=100,
            ),
        ),
    ]
