# Generated by Django 4.1.3 on 2023-01-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0014_technique_cost_technique_max_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique", name="power", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="technique",
            name="multitarget",
            field=models.CharField(
                choices=[("0", "1"), ("1", "2"), ("2", "3"), ("3", "4")],
                default="0",
                max_length=100,
            ),
        ),
    ]
