# Generated by Django 4.1.3 on 2023-01-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0016_alter_technique_power"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="boon",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
