# Generated by Django 4.1.3 on 2023-01-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unlimited", "0017_technique_boon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="summon",
            field=models.CharField(
                choices=[("0", "None"), ("1", "1"), ("2", "2"), ("3", "3")],
                default="0",
                max_length=100,
            ),
        ),
    ]
